tensorflow: drop Upstream-Status inside third_party .patch files
CAUTION: This email comes from a non Wind River email account!
Do not click links or open attachments unless you recognize the sender and know the content is safe.

* these patches create:
  third_party/0001-XNNPACK-support-32-bit-x86.patch
  third_party/0001-cpuinfo-support-32-bit-x86.patch
  third_party/eigen3/0001-workaround-ice-failure-while-building-from-source-wi.patch

  which aren't applied by do_patch bitbake task but by bazel:

  tensorflow $ grep patch_file tensorflow/workspace2.bzl | head -n 2
  tensorflow/workspace2.bzl: patch_file = ["//third_party:0001-XNNPACK-support-32-bit-x86.patch"],
  tensorflow/workspace2.bzl: patch_file = ["//third_party:0001-cpuinfo-support-32-bit-x86.patch"],
  third_party/eigen3/workspace.bzl: patch_file = ["//third_party/eigen3:0001-workaround-ice-failure-while-building-from-source-wi.patch"],

  so they don't really need Upstream-Status and including it there
  might cause false possitive e.g. in
  0001-fix-XNNPACK-build-failure-for-qemuarm.patch

  ERROR: tensorflow-lite-2.10.0-r0 do_patch: QA Issue: Malformed Upstream-Status in patch
  recipes-framework/tensorflow/tensorflow-lite/0001-fix-XNNPACK-build-failure-for-qemuarm.patch
  Please correct according to https://docs.yoctoproject.org/contributor-guide/recipe-style-guide.html#patch-upstream-status :
   Upstream-Status: Inappropriate [oe specific] [patch-status]
  ERROR: tensorflow-lite-2.10.0-r0 do_patch: Fatal QA errors were found, failing task.

  caused by extra space before Upstream-Status

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>