tensorflow/tensorflow-lite: fix XNNPACK build for qemuarm
...
|external/XNNPACK/src/qs8-igemm/gen/4x8c4-minmax-rndnu-aarch32-neondot-ld64.S:140:
Error: selected processor does not support `vsdot.s8 q8,q2,d0[0]' in ARM
mode
...

Does not support 32 bit ARM with Neon DotProduct

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>