classes/bazel.bbclass: fix noexecstack
Build keras/keras-native failed
...
ImportError: libtensorflow_cc.so.2: cannot enable executable stack as shared object requires: Invalid argument
...

Build tensorflow with option noexecstack

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>