tensorflow-lite: don't install flatbuffers header files
https://lists.yoctoproject.org/g/yocto-patches/message/2186
breaks a build for recipes which depend on both tensorflow-lite and flatbuffers because of conflicts in RSS as in:
ERROR: foo-1.0-r0 do_prepare_recipe_sysroot: The file /usr/include/flatbuffers/array.h is installed by both tensorflow-lite and flatbuffers, aborting

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>
Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>