tensorflow: fix compile failure
...
|tensorflow/lite/toco/graph_transformations/resolve_tensorflow_matmul.cc:177:48:
error: ignoring return value of 'constexpr __gnu_cxx::__normal_iterator<_Iterator, _Container>
__gnu_cxx::__normal_iterator<_Iterator, _Container>::operator+(difference_type) const [with
_Iterator = std::unique_ptr<toco::Operator>*; _Container = std::vector<std::unique_ptr<toco::Operator> >;
difference_type = long int]', declared with attribute 'nodiscard' [-Werror=unused-result]
...

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>