tensorflow.inc; fix compile failure on clang 22
Compile failed with clang 22:
```
|external/com_google_highway/hwy/ops/x86_512-inl.h:3132:24: error: always_inline
function '_mm512_load_ps' requires target feature 'avx512f', but would be inlined
into function 'Load' that is compiled without support for 'avx512f'
| 3132 |   return Vec512<float>{_mm512_load_ps(aligned)};
```

Backport 5 patches from upstream https://github.com/google/highway
to fix the issue

 4201022d Detect clang 19/20/21, also allow user override
 6c595a1b Increase the clang version number to check for to disable `SVE/SVE2` tests.
 16bbb825 Update target attributes for changed clang AVX10.2 policy. Fixes #2697
 ad48f2bf workaround for inadvertent SVE codegen on GCC<14. Fixes #2689, thanks @kleisauke
 bd28820d mark avx10.2 broken prior to gcc 15.2, clang 20. Fixes #2671

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>